"use strict";
/* Computability & Complexity quiz (חישוביות וסיבוכיות) — vanilla JS, no modules, no runtime deps.
   Loads window.CC_QUIZ = {meta, contexts, questions} from questions.js (generated by
   tools/build_questions.py — never hand-edit it). Ported from databases-quiz:
   - math is PRE-RENDERED MathML inside the *Html fields (questionHtml, option .html,
     explanationHtml, context textHtml/captionHtml/titleHtml). Nothing renders math at runtime.
   - answers are stored by stable option id (correctId / acceptedIds); options are
     Fisher–Yates shuffled on every render unless q.lockOrder (an option cites siblings by letter).
   - duplicates across exams are kept (full-exam replay); dedupePool() de-dups topic/random pools. */

const DATA = (window.CC_QUIZ && typeof window.CC_QUIZ === "object") ? window.CC_QUIZ : { meta:{}, contexts:{}, questions:[] };
const QS  = Array.isArray(DATA.questions) ? DATA.questions : [];
const CTX = (DATA.contexts && typeof DATA.contexts === "object") ? DATA.contexts : {};
const META = DATA.meta || {};
const HE_KEYS = ["א","ב","ג","ד","ה","ו","ז","ח"];
const STORE = "ccq_progress_v1";
const THEME_KEY = "ccq_theme";

/* Closed topic list — keep in sync: build_questions.py, validate.py, app.js, build_learn.py */
const TOPICS = [
  ["all","כל הנושאים"],
  ["tm",'מכונות טיורינג, וריאנטים ומ"ט א"ד'],
  ["decidability","כריעות וקבלה: R, RE, coRE"],
  ["enumerators","אנומרטורים"],
  ["undecidability","אי-כריעות: לכסון ובעיית העצירה"],
  ["mapping_reductions","רדוקציות מיפוי (≤m)"],
  ["closure","תכונות סגור"],
  ["classification","סיווג שפות"],
  ["time_p","סיבוכיות זמן והמחלקה P"],
  ["np","המחלקה NP ו-coNP"],
  ["poly_reductions","רדוקציות פולינומיות (≤p)"],
  ["npc","NP-שלמות"],
];
const TOPIC_LABEL = Object.fromEntries(TOPICS.map(([k,l])=>[k,l]));
/* Label -> HTML. "≤m" / "≤p" are bidi-neutral+Latin; unisolated in an RTL line they render
   mirrored and reordered as "(m≥)". Isolate them LTR. */
function labelHtml(l){ return escapeHtml(l).replace(/≤[mp]/g, m=>`<bdi dir="ltr">${m}</bdi>`); }
function topicLabelOf(q){ return TOPIC_LABEL[q.topic] || q.topicLabel || q.topic; }

const SRC_NOTE = {
  "solution-pdf":"מקור התשובה: פתרון רשמי של המבחן",
  "highlighted-pdf":"מקור התשובה: תשובה מסומנת בקובץ המבחן",
  "corrected-key":"מקור התשובה: מפתח תשובות מתוקן",
  "letter-table":"מקור התשובה: טבלת תשובות",
  "explanation-inferred":"מקור התשובה: הוסקה מתוך ההסבר — לא רשמית",
};

/* ---------- storage ---------- */
function freshProgress(){ return {stats:{answered:0,correct:0},perQ:{}}; }
function loadProgress(){
  try{ const p=JSON.parse(localStorage.getItem(STORE)); return (p && p.stats && p.perQ) ? p : freshProgress(); }
  catch(e){ return freshProgress(); }
}
function saveProgress(){ try{ localStorage.setItem(STORE, JSON.stringify(P)); }catch(e){} }
let P = loadProgress();

/* ---------- helpers ---------- */
const $ = s => document.querySelector(s);
function shuffle(a){ a=a.slice(); for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function show(id){ document.querySelectorAll(".screen").forEach(s=>s.classList.add("hidden")); $("#"+id).classList.remove("hidden"); window.scrollTo({top:0,behavior:"smooth"}); }
function escapeHtml(s){ return String(s).replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m])); }
function optById(q,id){ return (q.options||[]).find(o=>o.id===id); }
function hasHebrew(s){ return /[֐-׿]/.test(String(s)); }
/* accepted answers: usually just [correctId]; some questions accept more than one
   (appeal / ambiguous key). Grade "chosen ∈ accepted". */
function acceptedIdsOf(q){ return (Array.isArray(q.acceptedIds) && q.acceptedIds.length) ? q.acceptedIds : [q.correctId]; }
function isAccepted(q,id){ return id!=null && acceptedIdsOf(q).includes(id); }

/* Duplicates are kept in the bank (a whole past paper must replay in full); topic/random
   practice pools show each distinct question once. */
function dedupePool(arr){
  const seen=new Set(), out=[];
  for(const q of arr){ const k=q.dedupKey||q.id; if(seen.has(k)) continue; seen.add(k); out.push(q); }
  return out;
}
function filterMatch(q, topic, opts){
  if(topic!=="all" && q.topic!==topic) return false;
  if(opts.officialOnly && !q.official) return false;
  if(opts.mistakesOnly){ const r=P.perQ[q.id]; if(!r || r.correct) return false; }
  return true;
}
function filteredPool(topic, opts){ return dedupePool(QS.filter(q=>filterMatch(q, topic, opts))); }
function countFor(topic, opts){ return filteredPool(topic, opts).length; }

/* ---------- rendering pieces (all *Html fields are trusted build output) ---------- */
function contextHtml(ctx){
  if(!ctx) return "";
  let h = `<div class="ctx ctx-${escapeHtml(ctx.kind||"text")}">`;
  if(ctx.title) h += `<div class="ctx-title">${ctx.titleHtml || escapeHtml(ctx.title)}</div>`;
  if(ctx.image) h += `<figure class="ctx-fig"><img class="q-img ctx-img" src="${escapeHtml(ctx.image)}" alt="${escapeHtml(ctx.caption||ctx.title||"")}" loading="lazy">`+
                     (ctx.caption?`<figcaption>${ctx.captionHtml || escapeHtml(ctx.caption)}</figcaption>`:"")+`</figure>`;
  if(ctx.text) h += `<div class="ctx-text">${ctx.textHtml || escapeHtml(ctx.text)}</div>`;
  h += `</div>`;
  return h;
}
function extrasHtml(q){
  return q.image ? `<figure class="q-fig"><img class="q-img" src="${escapeHtml(q.image)}" alt="" loading="lazy"></figure>` : "";
}
function questionHtml(q){ return q.questionHtml || escapeHtml(q.question||""); }
function optionHtml(o){
  if(!o) return "";
  const type = o.type || "text";
  if(type==="image") return `<img class="opt-img" src="${escapeHtml(o.value)}" alt="" loading="lazy">`;
  const body = o.html || escapeHtml(o.value);
  if(type==="math") return body;                                   // already an LTR .opt-math span
  if(!hasHebrew(o.value)) return `<span class="opt-ltr" dir="ltr">${body}</span>`;
  return body;
}

/* ---------- session state ---------- */
const S = { mode:"practice", topic:"all", pool:[], pos:0, current:null, streak:0, _views:null,
  exam:{count:20, minutes:90, answers:{}, endAt:0, timer:null} };

/* ---------- start screen ---------- */
function renderTopStats(){
  const a=P.stats.answered, c=P.stats.correct;
  const pct=a?Math.round(c/a*100):0;
  $("#topStats").innerHTML =
    `<div class="stat">נענו <b>${a}</b></div>`+
    `<div class="stat">דיוק <b>${pct}%</b></div>`+
    `<div class="stat">במאגר <b>${dedupePool(QS).length}</b></div>`;
}
function selectedOpts(){ return { officialOnly: $("#officialOnly").checked, mistakesOnly: S.mode==="practice" && $("#mistakesOnly").checked }; }
function renderTopicGrid(){
  const opts=selectedOpts();
  $("#topicGrid").innerHTML = TOPICS.map(([k,label])=>{
    const n=countFor(k, opts);
    const active = k===S.topic ? "active":"";
    const dis = n===0 && k!=="all" ? "disabled":"";
    return `<button class="topic-btn ${active}" data-topic="${k}" ${dis}>
      <span>${labelHtml(label)}</span><span class="cnt">${n}</span></button>`;
  }).join("");
  document.querySelectorAll(".topic-btn").forEach(b=>{
    b.onclick=()=>{ S.topic=b.dataset.topic; renderTopicGrid(); updatePoolInfo(); };
  });
}
function selectedExam(){ const el=$("#examPick"); return (S.mode==="exam" && el) ? el.value : ""; }
function examQuestions(code){ return QS.filter(q=>q.examCode===code); }
function qNum(q){ if(Number.isInteger(q.num)) return q.num; const m=String(q.id).match(/-Q(\d+)$/); return m?parseInt(m[1],10):0; }
function examLabelOf(q){ return q.examLabel || q.examCode || ""; }
/* Exam-picker order: sample papers first (no place in the chronology), then real exams
   oldest→newest, newest at the bottom — same rule as the sibling apps. */
function examOrder(code){
  const c=String(code);
  if(/^SAMP/.test(c)) return [0, 0, c];
  const m=c.match(/^(\d{2})/);
  return [1, m?2000+parseInt(m[1],10):9999, c];
}
function byExamOrder(a,b){ const x=examOrder(a), y=examOrder(b); return (x[0]-y[0]) || (x[1]-y[1]) || String(x[2]).localeCompare(String(y[2])); }
function populateExamPick(){
  const sel=$("#examPick"); if(!sel) return;
  const seen=new Map();
  QS.forEach(q=>{ if(q.examCode && !seen.has(q.examCode)) seen.set(q.examCode, examLabelOf(q)); });
  const keep=sel.value;
  sel.innerHTML = `<option value="">אקראי (כל המאגר)</option>` +
    [...seen.entries()].sort((a,b)=>byExamOrder(a[0],b[0]))
      .map(([code,label])=>`<option value="${escapeHtml(code)}">${escapeHtml(label)} (${examQuestions(code).length})</option>`).join("");
  if(keep && seen.has(keep)) sel.value=keep;
  sel.onchange=()=>{ syncExamOpts(); updatePoolInfo(); };
}
function syncExamOpts(){ const wrap=$("#examCountWrap"); if(wrap) wrap.style.display = selectedExam() ? "none" : ""; }
function updatePoolInfo(){
  const info=$("#poolInfo"), btn=$("#startBtn");
  if(!QS.length){ info.textContent="המאגר עדיין ריק — אין שאלות לתרגול."; btn.disabled=true; return; }
  const code=selectedExam();
  if(code){
    const n=examQuestions(code).length;
    info.textContent = `${examLabelOf(QS.find(q=>q.examCode===code)||{})} — ${n} שאלות (מבחן מלא).`;
    btn.disabled = n===0;
    return;
  }
  const opts=selectedOpts();
  const pool=filteredPool(S.topic,opts);
  const off=pool.filter(q=>q.official).length;
  info.textContent = `נבחרו ${pool.length} שאלות (${off} מפתרון רשמי, ${pool.length-off} לא רשמיות).`;
  btn.disabled = pool.length===0;
}
function renderEmptyState(){
  const card=$("#screen-start .card");
  let box=$("#emptyState");
  if(QS.length){ if(box) box.remove(); return; }
  if(!box){
    box=document.createElement("div"); box.id="emptyState"; box.className="empty-state";
    box.innerHTML="<strong>המאגר עדיין ריק</strong>שאלות המבחנים נמצאות בתהליך הקלדה — חזרו בקרוב.";
    card.insertBefore(box, card.querySelector("h2").nextSibling);
  }
}
function initStart(){
  renderEmptyState();
  renderTopStats();
  populateExamPick();
  renderTopicGrid();
  syncExamOpts();
  updatePoolInfo();
  document.querySelectorAll('input[name=mode]').forEach(r=>{
    r.onchange=()=>{ S.mode=document.querySelector('input[name=mode]:checked').value;
      $("#examOpts").classList.toggle("hidden", S.mode!=="exam");
      $("#mistakesOnly").parentElement.style.display = S.mode==="exam"?"none":"";
      renderTopicGrid(); syncExamOpts(); updatePoolInfo();
    };
  });
  $("#officialOnly").onchange = ()=>{ renderTopicGrid(); updatePoolInfo(); };
  $("#mistakesOnly").onchange = ()=>{ renderTopicGrid(); updatePoolInfo(); };
  $("#startBtn").onclick = startSession;
  const nExams=new Set(QS.map(q=>q.examCode)).size;
  $("#datasetInfo").textContent = QS.length ? `${QS.length} שאלות · ${nExams} מבחנים` : "המאגר ריק";
}

/* ---------- session ---------- */
function startSession(){
  if(!QS.length) return;
  S._views=null;
  const opts=selectedOpts();
  const pickedExam = selectedExam();
  let pool;
  if(pickedExam){
    // full-exam mode replays EVERY question of that paper, duplicates included
    pool = examQuestions(pickedExam).slice().sort((a,b)=>qNum(a)-qNum(b));
  } else {
    pool = shuffle(filteredPool(S.topic, opts));
  }
  if(!pool.length) return;
  if(S.mode==="exam"){
    if(pickedExam){ S.exam.count = pool.length; }
    else { S.exam.count = Math.min(parseInt($("#examCount").value,10), pool.length); pool = pool.slice(0, S.exam.count); }
    S.exam.minutes = parseInt($("#examMinutes").value,10);
    S.exam.answers = {};
    S.exam.endAt = Date.now() + S.exam.minutes*60000;
    startTimer();
  }
  S.pool = pool; S.pos = 0;
  $("#prevBtn").classList.toggle("hidden", S.mode!=="exam");
  show("screen-quiz");
  renderQuestion();
}

function makeView(q){
  // shuffle by stable option id; skipped when an option cites its siblings by printed
  // letter ("תשובות א ו-ב נכונות") — shuffling would make that reference nonsense.
  const ids = (q.options||[]).map(o=>o.id);
  const order = q.lockOrder ? ids : shuffle(ids);
  const correctSet = new Set(order.map((id,i)=>isAccepted(q,id)?i:-1).filter(i=>i>=0));
  return { q, order, correctDisplay: order.indexOf(q.correctId), correctSet, answered:false, chosen:null };
}

function renderQuestion(){
  const q = S.pool[S.pos];
  if(S.mode==="exam"){
    S._views = S._views || {};
    S.current = S._views[q.id] || makeView(q);   // stable shuffle on back-navigation
    S._views[q.id] = S.current;
  } else {
    S.current = makeView(q);
  }
  const v=S.current;

  $("#qTopic").innerHTML = labelHtml(topicLabelOf(q));
  $("#qSource").textContent = examLabelOf(q) + (Number.isInteger(q.num) ? ` · שאלה ${q.num}` : "");
  const badge=$("#qBadge");
  badge.textContent = q.official ? "מפתרון רשמי" : "תשובה לא רשמית";
  badge.className = "chip " + (q.official?"official":"unofficial");
  $("#qConf").classList.toggle("hidden", q.confidence!=="low");

  $("#qContext").innerHTML = q.contextId ? contextHtml(CTX[q.contextId]) : "";
  $("#questionText").innerHTML = questionHtml(q);
  $("#questionText").dataset.qid = q.id;   // read by tools/verify_dom.js / shoot.js
  $("#qExtras").innerHTML = extrasHtml(q);

  $("#optionsList").innerHTML = v.order.map((oid,disp)=>
    `<button class="opt" data-disp="${disp}" data-oid="${escapeHtml(oid)}">
       <span class="key">${HE_KEYS[disp]||disp+1}</span>
       <span class="txt">${optionHtml(optById(q,oid))}</span>
     </button>`).join("");
  document.querySelectorAll("#optionsList .opt").forEach(b=> b.onclick=()=>choose(parseInt(b.dataset.disp,10)));

  const fb=$("#feedback"); fb.className="feedback hidden"; fb.innerHTML="";

  if(S.mode==="exam" && q.id in S.exam.answers){
    markExamChoice(v.order.indexOf(S.exam.answers[q.id]));
  }

  $("#progressFill").style.width = ((S.pos)/(S.pool.length))*100 + "%";
  if(S.mode==="exam"){
    $("#quizMeta").innerHTML = `שאלה ${S.pos+1}/${S.pool.length} <span id="tmr" class="timer"></span>`;
    renderTimer();
    $("#nextBtn").classList.toggle("hidden", S.pos>=S.pool.length-1);
    $("#submitExamBtn").classList.toggle("hidden", S.pos<S.pool.length-1);
    $("#prevBtn").disabled = S.pos===0;
    $("#streakBox").textContent = `נענו ${Object.keys(S.exam.answers).length}/${S.pool.length}`;
  } else {
    $("#quizMeta").textContent = `שאלה ${S.pos+1} מתוך ${S.pool.length}`;
    $("#nextBtn").classList.add("hidden");
    $("#submitExamBtn").classList.add("hidden");
    const a=P.stats.answered,c=P.stats.correct;
    $("#streakBox").textContent = `רצף נכון: ${S.streak||0} · דיוק כולל ${a?Math.round(c/a*100):0}%`;
  }
}

/* ---------- answering ---------- */
function choose(disp){
  const v=S.current, q=v.q;
  if(S.mode==="exam"){
    S.exam.answers[q.id] = v.order[disp];   // store the chosen option ID, never the position
    markExamChoice(disp);
    $("#streakBox").textContent = `נענו ${Object.keys(S.exam.answers).length}/${S.pool.length}`;
    return;
  }
  if(v.answered) return;
  v.answered=true; v.chosen=disp;
  const correct = isAccepted(q, v.order[disp]);
  document.querySelectorAll("#optionsList .opt").forEach((b,i)=>{
    b.disabled=true;
    if(v.correctSet.has(i)) b.classList.add("correct");
    else if(i===disp) b.classList.add("wrong");
  });
  recordAnswer(q, correct);
  S.streak = correct ? (S.streak||0)+1 : 0;
  const fb=$("#feedback");
  fb.className = "feedback " + (correct?"good":"bad");
  const srcNote = SRC_NOTE[q.answerSource] || "";
  const multi = acceptedIdsOf(q).length>1;
  fb.innerHTML = `<div class="verdict">${correct?"✓ נכון":"✗ לא נכון"}</div>`+
    (q.explanationHtml ? `<div class="expl">${q.explanationHtml}</div>` : `<div class="expl expl-none">אין הסבר במקור.</div>`)+
    (multi?`<span class="accept-note">בשאלה זו התקבלה יותר מתשובה אחת כנכונה.</span>`:"")+
    (q.official?"":`<span class="note">⚠ תשובה לא רשמית — מומלץ לאמת מול המקור.</span>`)+
    (q.confidence==="low"?`<span class="note">⚠ רמת ביטחון נמוכה בתשובה המסומנת.</span>`:"")+
    (srcNote?`<span class="note">${escapeHtml(srcNote)}</span>`:"")+
    `<span class="note">מקור: ${escapeHtml(examLabelOf(q))}${Number.isInteger(q.num)?` · שאלה ${q.num}`:""}</span>`;
  $("#nextBtn").classList.remove("hidden");
  $("#nextBtn").focus();
  renderTopStats();
  const a=P.stats.answered,c=P.stats.correct;
  $("#streakBox").textContent = `רצף נכון: ${S.streak} · דיוק כולל ${a?Math.round(c/a*100):0}%`;
}
function markExamChoice(disp){ document.querySelectorAll("#optionsList .opt").forEach((b,i)=> b.classList.toggle("chosen-exam", i===disp)); }
function recordAnswer(q, correct){ P.stats.answered++; if(correct) P.stats.correct++; P.perQ[q.id]={correct, t:Date.now()}; saveProgress(); }

/* ---------- navigation ---------- */
function next(){
  if(S.mode==="practice"){
    if(!S.current || !S.current.answered) return;
    if(S.pos>=S.pool.length-1){ S.pool = shuffle(S.pool); S.pos=0; } else S.pos++;
    renderQuestion();
  } else if(S.pos<S.pool.length-1){ S.pos++; renderQuestion(); }
}
function prev(){ if(S.mode==="exam" && S.pos>0){ S.pos--; renderQuestion(); } }

/* ---------- timer (exam) ---------- */
function startTimer(){ clearInterval(S.exam.timer); S.exam.timer=setInterval(renderTimer,1000); }
function renderTimer(){
  const el=$("#tmr"); if(!el) return;
  let ms=S.exam.endAt-Date.now();
  if(ms<=0){ ms=0; clearInterval(S.exam.timer); submitExam(true); return; }
  const m=Math.floor(ms/60000), s=Math.floor(ms%60000/1000);
  el.textContent = `⏱ ${m}:${String(s).padStart(2,"0")}`;
  el.classList.toggle("danger", ms<60000);
}

/* ---------- exam grading ---------- */
function submitExam(auto){
  clearInterval(S.exam.timer);
  if(!auto){
    const unans=S.pool.length-Object.keys(S.exam.answers).length;
    if(unans>0 && !confirm(`נותרו ${unans} שאלות ללא מענה. להגיש בכל זאת?`)){ startTimer(); return; }
  }
  let correct=0; const byTopic={}; const review=[];
  S.pool.forEach(q=>{
    const chosen = q.id in S.exam.answers ? S.exam.answers[q.id] : null;  // option id or null
    const ok = isAccepted(q, chosen);
    if(ok) correct++;
    recordAnswer(q, ok);
    (byTopic[q.topic] = byTopic[q.topic] || {n:0,c:0}); byTopic[q.topic].n++; if(ok) byTopic[q.topic].c++;
    review.push({q, chosen, ok});
  });
  renderResults(correct, byTopic, review);
  renderTopStats();
  show("screen-results");
}
function renderResults(correct, byTopic, review){
  const total=S.pool.length, pct=total?Math.round(correct/total*100):0;
  $("#resultsSummary").innerHTML =
    `<div class="scorering" style="--p:${pct}"><span>${pct}%</span></div>`+
    `<div class="txt"><b>${correct} / ${total}</b> תשובות נכונות<br>`+
    `<span style="color:var(--muted)">${pct>=60?"עברת! 🎉":"עוד קצת תרגול 💪"}</span></div>`;
  $("#resultsByTopic").innerHTML = Object.entries(byTopic).map(([t,o])=>{
    const p=Math.round(o.c/o.n*100);
    return `<div class="tline"><span>${labelHtml(TOPIC_LABEL[t]||t)}</span><span class="tbar"><i style="width:${p}%"></i></span><span>${o.c}/${o.n}</span></div>`;
  }).join("");
  $("#resultsReview").innerHTML = review.map(r=>{
    const v=r.q;
    const chosenTxt = r.chosen!=null ? optionHtml(optById(v,r.chosen)) : "— לא נענתה —";
    const acc = acceptedIdsOf(v);
    const correctTxt = acc.map(id=>optionHtml(optById(v,id))).join(`<span class="or">או</span>`);
    return `<div class="rev ${r.ok?"ok":"bad"}">
      <div class="rq">${questionHtml(v)}</div>
      ${v.contextId?contextHtml(CTX[v.contextId]):""}
      ${extrasHtml(v)}
      <div class="ra"><span class="${r.ok?"good":"miss"}">תשובתך: ${chosenTxt}</span>`+
      (r.ok?"":` · <span class="good">${acc.length>1?"נכונות":"הנכונה"}: ${correctTxt}</span>`)+
      (v.explanationHtml?`<br>${v.explanationHtml}`:"")+(v.official?"":" (לא רשמי)")+`</div></div>`;
  }).join("");
}

/* ---------- controls ---------- */
function quit(){ clearInterval(S.exam.timer); S._views=null; S.streak=0; initStart(); show("screen-start"); }
function openLightbox(src, alt){
  const lb=$("#lightbox"), img=$("#lightboxImg"); if(!lb||!img) return;
  img.src=src; img.alt=alt||""; lb.classList.remove("hidden");
}
function closeLightbox(){ const lb=$("#lightbox"); if(!lb) return; lb.classList.add("hidden"); $("#lightboxImg").src=""; }
function bindGlobal(){
  $("#nextBtn").onclick=next;
  $("#prevBtn").onclick=prev;
  $("#submitExamBtn").onclick=()=>submitExam(false);
  $("#quitBtn").onclick=()=>{ if(S.mode!=="exam"||confirm("לצאת מהמבחן? ההתקדמות לא תישמר.")) quit(); };
  $("#backHomeBtn").onclick=quit;
  function goHome(){
    const inExamQuiz = S.mode==="exam" && !$("#screen-quiz").classList.contains("hidden");
    if(inExamQuiz && !confirm("לצאת מהמבחן? ההתקדמות לא תישמר.")) return;
    quit();
  }
  const brand=$("#brandHome");
  if(brand){
    brand.style.cursor="pointer";
    brand.onclick=goHome;
    brand.onkeydown=e=>{ if(e.key==="Enter"||e.key===" "){ e.preventDefault(); goHome(); } };
  }
  $("#resetProgress").onclick=()=>{ if(confirm("לאפס את כל ההתקדמות וההיסטוריה?")){ P=freshProgress(); saveProgress(); renderTopStats(); renderTopicGrid(); updatePoolInfo(); } };
  // click any figure (question / context / learn) to zoom
  document.addEventListener("click", e=>{
    const img=e.target.closest(".q-img, .learn-fig img"); if(!img) return;
    openLightbox(img.src, img.alt);
  });
  const lb=$("#lightbox");
  if(lb) lb.addEventListener("click", e=>{ if(e.target===lb) closeLightbox(); });
  const lbClose=$("#lightboxClose"); if(lbClose) lbClose.onclick=closeLightbox;
  document.addEventListener("keydown",e=>{
    if(lb && !lb.classList.contains("hidden")){ if(e.key==="Escape") closeLightbox(); return; }
    if($("#screen-quiz").classList.contains("hidden")) return;
    if(e.target && /^(SELECT|INPUT|TEXTAREA)$/.test(e.target.tagName)) return;
    if(/^[1-8]$/.test(e.key)){ const b=document.querySelector(`#optionsList .opt[data-disp="${+e.key-1}"]`); if(b && !b.disabled) b.click(); }
    else if(e.key==="Enter"){ if(!$("#nextBtn").classList.contains("hidden")) next(); else if(!$("#submitExamBtn").classList.contains("hidden")) submitExam(false); }
    else if(e.key==="ArrowLeft" && !$("#nextBtn").classList.contains("hidden")) next();
    else if(e.key==="ArrowRight" && S.mode==="exam") prev();
  });
}

/* ---------- theme toggle ---------- */
(function initTheme(){
  const btn = document.getElementById("themeToggle");
  if(!btn) return;
  const root = document.documentElement;
  const systemDark = () => !window.matchMedia || !window.matchMedia("(prefers-color-scheme: light)").matches;
  const effective = () => root.dataset.theme || (systemDark() ? "dark" : "light");
  const paint = () => { btn.textContent = effective()==="dark" ? "🌙" : "☀️"; };
  paint();
  btn.addEventListener("click", () => {
    const nxt = effective()==="dark" ? "light" : "dark";
    root.dataset.theme = nxt;
    try{ localStorage.setItem(THEME_KEY, nxt); }catch(e){}
    paint();
  });
  if(window.matchMedia){
    const mq=window.matchMedia("(prefers-color-scheme: light)");
    if(mq && mq.addEventListener) mq.addEventListener("change", () => { if(!root.dataset.theme) paint(); });
  }
})();

/* ---------- learning section ----------
   learn.js (generated by tools/build_learn.py from docs/briefs/*.md) provides
   window.LEARN = {chapters:[{id,title,topic,kind,html}], meta} (a bare array is also accepted).
   The entry button hides itself while there are no chapters. Clicks inside a brief are
   delegated: .qref peeks at a real exam question, .xref jumps to another chapter,
   .learn-drill starts a topic drill. Deep link: index.html?learn=<chapterId>. */
function learnChapters(){
  const L=window.LEARN;
  if(Array.isArray(L)) return L;
  return (L && Array.isArray(L.chapters)) ? L.chapters : [];
}
let openLearnAt = null;   // set by initLearn; used by the ?learn= deep link
(function initLearn(){
  const data = learnChapters();
  const entry = document.getElementById("learnEntry");
  const screen = document.getElementById("screen-learn");
  if(!entry || !screen) return;
  if(!data.length){ entry.style.display = "none"; return; }

  const toc=$("#learnToc"), content=$("#learnContent"), fill=$("#learnProgressFill"), pos=$("#learnPos");
  const prevB=$("#learnPrev"), nextB=$("#learnNext"), toggle=$("#learnTocToggle"), backdrop=$("#learnBackdrop");
  const backB=$("#learnBackBtn");
  let idx=0, built=false;

  function buildToc(){
    toc.innerHTML = data.map((s,i)=>
      `<button data-i="${i}"${s.kind==="cheat"?' class="cheat"':''}>${labelHtml(s.title)}</button>`).join("");
    toc.querySelectorAll("button").forEach(b=> b.onclick=()=>{ go(+b.dataset.i); closeDrawer(); });
    built=true;
  }
  function go(i){
    idx=Math.max(0,Math.min(data.length-1,i));
    const s=data[idx];
    // each brief is written to be read then drilled, so surface the drill entry point
    const n = s.topic ? countFor(s.topic,{officialOnly:false,mistakesOnly:false}) : 0;
    const drill = n ? `<button type="button" class="btn primary learn-drill" data-topic="${escapeHtml(s.topic)}">תרגל נושא זה ▶ <span class="n">${n}</span></button>` : "";
    const kind = s.kind==="cheat" ? `<span class="learn-kind">דף עזר</span>` : "";
    content.innerHTML = `<div class="learn-head"><h2 class="learn-h">${labelHtml(s.title)}${kind}</h2>${drill}</div>` + (s.html||"");
    content.dataset.chapter = s.id || "";
    toc.querySelectorAll("button").forEach((b,j)=> b.classList.toggle("active", j===idx));
    const active=toc.querySelector("button.active"); if(active) active.scrollIntoView({block:"nearest"});
    markScrollable();
    fill.style.width = ((idx+1)/data.length*100)+"%";
    pos.textContent = `${idx+1} / ${data.length}`;
    prevB.disabled=idx===0; nextB.disabled=idx===data.length-1;
    window.scrollTo({top:0,behavior:"smooth"}); content.focus({preventScroll:true});
  }
  /* Wide tables and display formulas scroll inside their own box. Flag the ones that
     actually overflow so CSS shows an edge shadow — a clipped formula with no hint reads as
     broken. Recomputed on resize (rotating a phone changes which ones overflow). */
  function markScrollable(){
    content.querySelectorAll(".math-block,.tbl-wrap").forEach(el=>
      el.classList.toggle("scrollable", el.scrollWidth > el.clientWidth + 1));
  }
  let rzT;
  window.addEventListener("resize", ()=>{
    clearTimeout(rzT);
    rzT=setTimeout(()=>{ if(!screen.classList.contains("hidden")) markScrollable(); }, 150);
  });
  function openLearn(){ if(!built) buildToc(); show("screen-learn"); go(idx); }
  function setDrawer(open){ toc.classList.toggle("open",open); backdrop.classList.toggle("hidden",!open); toggle.setAttribute("aria-expanded", open?"true":"false"); }
  function closeDrawer(){ setDrawer(false); }
  openLearnAt = id=>{
    const j=data.findIndex(c=>c.id===id);
    if(j<0) return false;
    idx=j; openLearn(); return true;
  };

  entry.onclick=openLearn;
  backB.onclick=()=>{ closeDrawer(); closePeek(); quit(); };
  prevB.onclick=()=>go(idx-1);
  nextB.onclick=()=>go(idx+1);
  toggle.onclick=()=>setDrawer(!toc.classList.contains("open"));
  backdrop.onclick=closeDrawer;

  /* ----- question peek: click a `26B-B-Q3` reference inside a brief ----- */
  const peek=$("#qpeek"), peekBody=$("#qpeekBody"), peekDrill=$("#qpeekDrill");
  let peekTopic=null;
  function openPeek(id){
    const q=QS.find(x=>x.id===id);
    if(!q || !peek) return;
    $("#qpeekId").textContent = q.id;
    $("#qpeekSource").textContent = examLabelOf(q) + (Number.isInteger(q.num) ? ` · שאלה ${q.num}` : "");
    const badge=$("#qpeekBadge");
    badge.textContent = q.official ? "מפתרון רשמי" : "תשובה לא רשמית";
    badge.className = "chip " + (q.official?"official":"unofficial");
    // source order with the accepted answer(s) marked: the brief discusses this exact
    // question, so shuffling here would only make it harder to follow.
    peekBody.innerHTML =
      (q.contextId ? contextHtml(CTX[q.contextId]) : "") +
      `<div class="qpeek-q">${questionHtml(q)}</div>` + extrasHtml(q) +
      `<ol class="qpeek-opts">` + (q.options||[]).map((o,i)=>
        `<li class="${isAccepted(q,o.id)?"right":""}" data-oid="${escapeHtml(o.id)}"><span class="key">${HE_KEYS[i]||i+1}</span>`+
        `<span class="txt">${optionHtml(o)}</span></li>`).join("") + `</ol>` +
      (q.explanationHtml ? `<div class="qpeek-exp"><strong>הסבר:</strong> ${q.explanationHtml}</div>` : "");
    peekTopic=q.topic;
    peekDrill.classList.toggle("hidden", !countFor(q.topic,{officialOnly:false,mistakesOnly:false}));
    peek.classList.remove("hidden");
    peekBody.scrollTop=0;
    $("#qpeekClose").focus({preventScroll:true});
  }
  function closePeek(){ if(!peek) return; peek.classList.add("hidden"); peekBody.innerHTML=""; peekTopic=null; }
  const peekOpen=()=> peek && !peek.classList.contains("hidden");
  if(peek){
    peek.addEventListener("click", e=>{ if(e.target===peek) closePeek(); });
    $("#qpeekClose").onclick=closePeek;
    peekDrill.onclick=()=>{ const t=peekTopic; closePeek(); closeDrawer(); startTopicPractice(t); };
  }

  content.addEventListener("click", e=>{
    const qref=e.target.closest(".qref");
    if(qref){ openPeek(qref.dataset.q); return; }
    const xref=e.target.closest(".xref");
    if(xref){
      e.preventDefault();
      const j=data.findIndex(c=>c.id===xref.dataset.chapter);
      if(j>=0) go(j);
      return;
    }
    const drill=e.target.closest(".learn-drill");
    if(drill){ closeDrawer(); startTopicPractice(drill.dataset.topic); }
  });
  document.addEventListener("keydown", e=>{
    const lb=$("#lightbox");
    if(lb && !lb.classList.contains("hidden")) return;       // bindGlobal closes the lightbox
    // the peek sits above the brief: Escape closes it, chapter nav stays put
    if(peekOpen()){ if(e.key==="Escape") closePeek(); return; }
    if(screen.classList.contains("hidden")) return;
    if(e.key==="ArrowLeft") go(idx+1);
    else if(e.key==="ArrowRight") go(idx-1);
    else if(e.key==="Escape"){ closeDrawer(); quit(); }
  });
})();

/* ---------- single entry point into a topic drill ---------- */
function startTopicPractice(topic){
  if(!TOPICS.some(([k])=>k===topic)) return false;
  if(countFor(topic,{officialOnly:false,mistakesOnly:false})===0) return false;
  S.mode="practice"; S.topic=topic;
  const r=document.querySelector('input[name=mode][value="practice"]'); if(r) r.checked=true;
  $("#examOpts").classList.add("hidden");
  $("#officialOnly").checked=false; $("#mistakesOnly").checked=false;
  initStart();
  startSession();
  return true;
}
/* deep links: index.html?practice=<topicKey>  |  index.html?learn=<chapterId> */
function autoStartFromURL(){
  let t, c;
  try{ const u=new URLSearchParams(location.search); t=u.get("practice"); c=u.get("learn"); }catch(e){ return; }
  if(t) startTopicPractice(t);
  else if(c && openLearnAt) openLearnAt(c);
}

/* ---------- boot ---------- */
initStart(); bindGlobal(); autoStartFromURL();
